name: swaram
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  id3: ^1.0.2
  audioplayers: ^1.0.0
  sembast: ^3.2.0+1
  path_provider: ^2.0.11
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  msix: ^3.6.2

flutter:
  uses-material-design: true
